"""empty message

Revision ID: 88208a46c85a
Revises: 45d847696abe
Create Date: 2026-06-02 17:15:44.970058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88208a46c85a'
down_revision = '45d847696abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_users')
    # ### end Alembic commands ###
